environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      cassandra_version: 3.11.0
      ci_type: standard
    - PYTHON: "C:\\Python34"
      cassandra_version: 3.11.0
      ci_type: unit
os: Visual Studio 2015
platform:
  - x64
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: .\appveyor\appveyor.ps1
build_script:
  - cmd: |
      "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
      python setup.py install --no-cython
test_script:
  -  ps: .\appveyor\run_test.ps1
cache:
  - C:\Users\appveyor\.m2
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - C:\Users\appveyor\jce_policy-1.7.0.zip
  - C:\Users\appveyor\jce_policy-1.8.0.zip