name: Integration tests Python2

on:
  pull_request:
    branches:
     - master
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.pull_request.labels.*.name, 'disable-integration-tests')"
    steps:
    - uses: actions/checkout@v2
    - name: Install Python2.7
      uses: actions/setup-python@v4
      with:
        python-version: 2.7

    - name: Test with pytest
      run: |
        ./ci/run_integration_test.sh tests/integration/standard/test_authentication.py tests/integration/standard/test_cluster.py tests/integration/standard/test_concurrent.py tests/integration/standard/test_connection.py tests/integration/standard/test_control_connection.py tests/integration/standard/test_custom_payload.py tests/integration/standard/test_custom_protocol_handler.py tests/integration/standard/test_cython_protocol_handlers.py tests/integration/standard/test_scylla_cloud.py tests/integration/standard/test_use_keyspace.py tests/integration/standard/test_ip_change.py tests/integration/cqlengine/
        # can't run this, cause only 2 cpus on github actions: tests/integration/standard/test_shard_aware.py
